---
- hosts: 127.0.0.1
  connection: local
  
  vars_files:
    - vars.yml
  tasks: 

    - name: dump the wordpress mysql database
      command: mysqldump -u zimbi --password=mywebsite wordpress --result-file=/home/zimbi/dump/backup/mysqlwordpress_db.sql
    
    - name: dump the mysql mysql database
      command: mysqldump -u root --password=1234 mysql --result-file=/home/zimbi/dump/backup/mysqlmysql_db.sql

    - name: copy mysql.cnf
      command: cp /etc/mysql/mysql.cnf /home/zimbi/dump/backup/mysql.cnf
    
    - name: copy wp-config.php
      command: cp /var/www/html/wp-config.php /home/zimbi/dump/backup/wp-config.php
    
    
    - name: tar
      command: tar czf backup_{{date}}.tar.gz /home/zimbi/dump/backup
      args:
        chdir: /home/zimbi/
    

    
